//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int CartID { get; set; }
        public Nullable<int> MA_KH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> MA_SP { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
