//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON
    {
        public int MA_SP { get; set; }
        public int MA_HD { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public Nullable<double> THANH_TIEN { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
