//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_DICHVU
    {
        public LOAI_DICHVU()
        {
            this.DICH_VU = new HashSet<DICH_VU>();
        }
    
        public int MAlLOAI { get; set; }
        public string TEN_LOAI { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual ICollection<DICH_VU> DICH_VU { get; set; }
    }
}
