//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        public int MA_NV { get; set; }
        public string TEN_NV { get; set; }
        public string EMAIL { get; set; }
        public string USERNAME { get; set; }
        public byte[] PASSWORD { get; set; }
        public bool TRANGTHAI { get; set; }
        public Nullable<int> MA_CN { get; set; }
        public Nullable<int> QUYEN { get; set; }
    
        public virtual CHI_NHANH CHI_NHANH { get; set; }
    }
}
